project:
  type: website
  output-dir: docs

website:
  title: "AI with Aniket"
  favicon: assets/favicon.ico
  repo-url: https://github.com/aniketmaurya/blog
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/aniketmaurya
      - icon: twitter
        href: https://twitter.com/aniketmaurya
  image: profile.png
  twitter-card: true
  google-analytics: "UA-156199072-2"

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
