project:
  type: website
  output-dir: docs

website:
  title: "AI with Aniket"
  favicon: assets/favicon.ico
  repo-url: https://github.com/aniketmaurya/blog
  site-url: https://aniketmaurya.com

  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - pages/talks.qmd
      - about.qmd

    right:
      - icon: github
        href: https://github.com/aniketmaurya
      - icon: twitter
        href: https://twitter.com/aniketmaurya

  page-footer:
    left: "Copyright 2023, Aniket Maurya"
    right:
      - icon: github
        href: https://github.com/aniketmaurya
      - icon: twitter
        href: https://twitter.com/aniketmaurya

  image: /assets/blog.png
  open-graph: true
  twitter-card:
    site: "@aniketmaurya"
  google-analytics: "G-QD11JWMMPF"

format:
  html:
    theme:
      light: default
      dark: darkly
    css: styles.css
