project:
  type: website

website:
  title: "AI with Aniket"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/aniketmaurya
      - icon: twitter
        href: https://twitter.com/aniketmaurya
format:
  html:
    theme: cosmo
    css: styles.css



