---
title: "About"
image: https://avatars.githubusercontent.com/u/21018714?s=400&u=b47cb5eb401714a0e38aa8d32ec7031e5c30e346&v=4
about:
  template: solana
  image-shape: round
  links:
    - icon: twitter
      text: Twitter
      href: https://twitter.com/aniketmaurya
    - icon: linkedin
      text: LinkedIn
      href: https://linkedin.com/in/aniketmaurya
    - icon: github
      text: Github
      href: https://github.com/aniketmaurya
    - icon: youtube
      text: YouTube
      href: https://youtube.com/@aiwithaniket

---
Hi there! I'm Aniket, a self-taught **Machine Learning Engineer** with a background in Computer Science & Engineering.
<br>Currently, I'm working on open-source projects at **Lightning AI** as a **Developer Advocate**.

You can find most of my new blogs on LLMs, Distributed Training, and Machine Learning on [Lightning AI's blog](https://lightning.ai/pages/author/aniket-maurya/).

I enjoy building and deploying **machine learning systems at scale**.
In the past, I've created computer vision and NLP-based systems that automated significant portions of business operations for a major e-commerce company.
<br>I also enjoy tinkering with open-source tools and have both created and currently maintain several open-source projects,
including [Gradsflow](https://docs.gradsflow.com) and [Lit-GPT](https://github.com/Lightning-AI/lit-gpt).

## DevRel Experience

I joined Lightning AI (formerly PyTorch Lightning) after being a community contributor and core maintainer of [Lightning Flash](https://lightning-flash.readthedocs.io/en/latest/governance.html). I made significant contributions from the library's launch day and hosted meetups and workshops to educate developers.

I have been working on building the community, creating technical content, and using my engineering skills to build flagship products. Some of my achievements here are:

- Grew the London community by 10x and hosted multiple in-person community [meetups](https://www.meetup.com/london-deep-learning-by-lightning-ai/).
- Created high-quality content that drove the majority of the traffic to the [Lightning.ai](http://Lightning.ai) website. My blog was trending on [HackerNews](https://news.ycombinator.com/item?id=36068850) as well.
- Live-streamed about LLMs and distributed model training on our brand Discord channel, growing the community to more than 1K.
- Managed [Twitter](https://twitter.com/lightningAI/) and LinkedIn for posting technical content and driving engagements with the developer community.

## Engineering Experience

Before a DevRel, I am a Machine Learning engineer. I have worked with startups to build and deploy machine learning systems in production.
I successfully scaled ML services to handle millions of requests per hour by implementing a messaging queue, automatic batching, and various other optimizations.
My open-source project, [Chitra](https://github.com/aniketmaurya/chitra), is actively used in production environments.

I spearheaded the development of Lightning AI's flagship product, [Muse](https://github.com/Lightning-Universe/stable-diffusion-deploy).
I was responsible for deploying stable diffusion and scaling it to support 1K+ concurrent users.

Recently, my work has focused on **distributed training of LLMs and deployment**.
I contribute to [Lit-GPT](https://github.com/Lightning-AI/lit-gpt), an open-source LLM training and finetuning library developed by Lightning AI.
Additionally, I integrated the LLM evaluation framework LM-Eval Harness and [HELM](https://github.com/stanford-crfm/helm) (Stanford’s evaluation framework) to enhance the evaluation of LLMs.
